# Generated by Django 3.2.6 on 2021-09-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='supervisedPlot',
            field=models.JSONField(null=True),
        ),
    ]
