# Generated by Django 3.2.6 on 2021-09-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_interface_supervisedplot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='changePointPlot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='interface',
            name='sensorCounts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='interface',
            name='supervisedPlot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
