# Generated by Django 3.2.6 on 2021-09-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20210906_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='sensorCounts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
