# Generated by Django 3.2.6 on 2021-09-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_interface_sensorcountschangepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='sensorCountsChangePoint',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='interface',
            name='sensorData',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
