# Generated by Django 3.2.6 on 2021-09-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20210906_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='changepoint_hist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interface',
            name='occupied_hist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
