# Generated by Django 3.1.6 on 2021-02-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changepoint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changepoint',
            old_name='cal',
            new_name='changepoint',
        ),
    ]
