# Generated by Django 3.1.6 on 2021-02-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changepoint', '0006_changepoint_countsindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepoint',
            name='sensorCounts',
            field=models.JSONField(verbose_name='0xbfb8'),
        ),
    ]
