# Generated by Django 3.1.6 on 2021-02-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changepoint', '0008_auto_20210225_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepoint',
            name='countsIndex',
            field=models.IntegerField(),
        ),
    ]
