# Generated by Django 3.1.6 on 2021-02-26 03:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changepoint', '0010_auto_20210225_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepoint',
            name='sensorCounts',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=100), size=10),
        ),
    ]
