# Generated by Django 3.1.6 on 2021-02-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changepoint', '0015_auto_20210226_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changepoint',
            name='sensorCounts',
        ),
    ]
