# Generated by Django 3.1.6 on 2021-06-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changepoint', '0019_changepoint_sensorcounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepoint',
            name='changePointPlot',
            field=models.JSONField(null=True),
        ),
    ]
