# Generated by Django 3.1.6 on 2021-02-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_update', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update_test',
            old_name='cal',
            new_name='changepoint',
        ),
    ]
