# Generated by Django 3.2.6 on 2021-08-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkif',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='networkif',
            name='sensorReadings',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
