# Generated by Django 3.2.6 on 2021-08-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkif', '0002_auto_20210829_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkif',
            name='timestamp',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
