# Generated by Django 3.2.6 on 2021-09-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkif', '0004_auto_20210829_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkif',
            name='sensorData',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='networkif',
            name='timestamp',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
