# Generated by Django 3.2.6 on 2021-09-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervised', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervised',
            name='changePointPlot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='supervised',
            name='sensorCounts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
